### PR TITLE
OCM-3124: fix for additional_trust_bundle resulting in an error

### LINKED ISSUE #229: Provider produced inconsistent result after apply - additional_trust_bundle
When providing additional trusted certificates via the `proxy.additional_trust_bundle` attribute the provider attempts to store a different value in the state than what Terraform expects. Causing Terraform to exit with the error (I've replaced the certificate bodies with ...)

```shell
rhcs_cluster_rosa_classic.rosa_sts_cluster: Creating...

 Error: Provider produced inconsistent result after apply
 
 When applying changes to rhcs_cluster_rosa_classic.rosa_sts_cluster, provider "provider[\"registry.terraform.io/terraform-redhat/rhcs\"]" produced an unexpected new value: .proxy.additional_trust_bundle: was cty.StringVal("-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n"), but now cty.StringVal("REDACTED").

 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I'm using Terraform v1.5.3 with rhcs version 1.2.2.

### PR DESCRIPTION
**Pull request by sagidayan**
Since OCM returns `REDUCTED` as values of sensitive content, the provider was populating `REDUCTED` as the new state for `additional_trust_bundle`. 

This PR ensures that if there is a value in the state, do not override value from backend.

Should fix #229

### CODE REVIEW

**Review by nirarg — COMMENTED** [review]
Can we have subsystem to validate this?

File: provider/cluster_rosa_classic_resource.go [hunk 1]
```diff
@@ -1657,7 +1657,7 @@ func populateRosaClassicClusterState(ctx context.Context, object *cmv1.Cluster,
 	}
 
 	trustBundle, ok := object.GetAdditionalTrustBundle()
-	if ok {
+	if ok && common.IsStringAttributeEmpty(state.Proxy.AdditionalTrustBundle) {
```
Comment (bardielle) [inline provider/cluster_rosa_classic_resource.go:1660]: Please also open a PR for 1.2-prerelease branch (we would like to publish a fix)

Comment (sagidayan) [reply provider/cluster_rosa_classic_resource.go:1660]: Cant we cherry-pick after the merge?

Comment (osherdp) [reply provider/cluster_rosa_classic_resource.go:1660]: you can type right now ``<slash>cherry-pick v1.2.0-prerelease.1-branch`` and it will get applied after the merge

Comment (bardielle) [reply provider/cluster_rosa_classic_resource.go:1660]: Also, please add a commit with the changelog changes...
